### ISSUE TITLE
Can't run precompiled kernels.

### ISSUE THREAD

**Issue by etet100** [LdB-ECM/Raspberry-Pi#3]
Hi. I can't run any of GLES2 examples. My hardware is Raspberry 1 model B and
Raspberry Zero 1.3 512MB.

GLES2 - triangle is very distorted
GLES2_Model - some white distorted animated thing (as far as i remember)
GLES2_Rotate - white dots at top of the screen

Do you know how to fix it?

**Comment by LdB-ECM** [comment]
I will have a quick look at, I have been mainly on a Pi3 but I do have a Pi1.

**Comment by etet100** [comment]
Hi. Any news?

**Comment by LdB-ECM** [comment]
I have now tried on 2 different Pi1's from different age and it works fine.

I have to assume it is a screen resolution issue.

The default setup for the code is to take whatever the detected screen resolution is which seem to always be 16 bit colour and ask for the same settings in 32bit colour. I hadn't really thought about it but you could get the situation a monitor can do X * Y in 16 bit colour but not X * Y in 32 bit colour.

I am looking into how to make a better screen size auto-detect because I specifically need 24 or 32 bit colour mode.

In the meantime you could either compile with your own fixed screen resolution (Replacing my zeros for auto detect) in the screen initialize or give me the X * Y resolution your screen supports and I will compile and put the sample up for you.

**Comment by etet100** [comment]
I have very old Raspberry 1 Model B and much more recent Raspberry Zero v1.3. At least 2 different LCD displays (Samsung 32 tv and Eizo Foris FS2331). Resolutions supported by Eizo:
640 × 480 60 Hz 
720 × 400 70 Hz
800 × 600 60 Hz
1024 × 768 60 Hz
1280 × 720 60 Hz
1280 × 960 60 Hz
1280 × 1024 60 Hz
1680 × 1050 60 Hz
1920 × 1080 (recommended) 60 Hz

I will try to set fixed resolution.

![eizo](https://user-images.githubusercontent.com/22624537/33058744-65640f42-ce91-11e7-9801-e16df29f65f0.png)

**Comment by LdB-ECM** [comment]
That is really strange I am testing on an old  Pi1B
Board:
https://github.com/LdB-ECM/Docs_and_Images/blob/master/Images/Pi1.jpg
It running:
https://github.com/LdB-ECM/Docs_and_Images/blob/master/Images/Pi1_working.jpg

Do any of the other blinker or graphics files work .. that is are you only having trouble when I need the screen in hi color mode?

**Comment by etet100** [comment]
Hi. myBlinker example:
![img_20171125_095604](https://user-images.githubusercontent.com/22624537/33229045-61edebc4-d1c7-11e7-80cd-30fb33cfc71a.jpg)

Changing PiConsole_Init(0, 0, 0, &printf) to PiConsole_Init(1366, 768, 0, &printf) or PiConsole_Init(1366, 768, 16, &printf) or PiConsole_Init(1366, 768, 32, &printf) doesn't fix it.

**Comment by LdB-ECM** [comment]
Okay I can see the problem which is the screen width isn't mod 16 so the line offsets roll

Most normal screen width  800, 1024, 1280 etc are mod 16  ... Easy fix ... doing it now.

**Comment by etet100** [comment]
I'm sorry, i didn't noticed that you have edited your comment. Blinker example is finally working.

**Comment by LdB-ECM** [comment]
Okay I will fix the other examples tonight, I had some updates for them anyhow.

**Comment by LdB-ECM** [comment]
Fixes done and now up.
